### ISSUE TITLE
{% endcomment %} tag for automatic deployment

### ISSUE THREAD

**Issue by JREAM** [codezeus/django-project-template#4]
## This part goes well

```
pip install virtualenvwrapper.codezeus
mkproject -t codezeus_django django_apps

Applying template codezeus_django
virtualenvwrapper.django --- Installing Django 1.9.7
Collecting django==1.9.7
  Using cached Django-1.9.7-py2.py3-none-any.whl
Installing collected packages: django
Successfully installed django-1.9.7
virtualenvwrapper.django --- Grabbing project template from Github
Traceback (most recent call last):
  File "/home/jesse/.virtualenvs/django_apps/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/core/management/commands/startproject.py", line 33, in handle
    super(Command, self).handle('project', project_name, target, **options)
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/core/management/templates.py", line 164, in handle
    template = Engine().from_string(content)
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/template/engine.py", line 176, in from_string
    return Template(template_code, engine=self)
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/template/base.py", line 510, in parse
    self.invalid_block_tag(token, command, parse_until)

```

## This part has an error:
```
File "/home/jesse/.virtualenvs/django_apps/local/lib/python2.7/site-packages/django/template/base.py", line 572, in invalid_block_tag
    "or load this tag?" % (token.lineno, command)
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 109: 'endcomment'. Did you forget to register or load this tag?
```

**Comment by JREAM** [comment]
Fixed, There were 2 in the README.md not sure how they got there, works now.
